esphome:
  name: rd03e-2
  friendly_name: Radar Presence Sensor
  includes:
    - components/rd03e_radar/
  libraries:
    - "ArduinoJson@6.18.5"

external_components:
  - source: components
    components: rd03e_radar
        
esp32:
  board: esp32dev
  framework:
    type: arduino


# Enable logging
logger:
  hardware_uart: UART0
  level: DEBUG

# Enable Home Assistant API
api:
  # encryption:
  #   key: "gtgCF3Fu6e9GK6RllKSq2yaAtM5qrHTI7hGjlIuPTY8="

ota:
  # - platform: esphome
  #   password: "f0823919fb5d0b5454ba7947cfca9279"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip: 
    gateway: 192.168.1.254
    subnet: 255.255.255.0
    static_ip: 192.168.1.32
    dns1: 192.168.1.145
    dns2: 192.168.1.254

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rd03E-2 Fallback Hotspot"
    password: "qzonrYJ7SAIh"

captive_portal:

# Define the UART for communication with RD03-E sensor
uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 256000
  data_bits: 8
  parity: NONE
  stop_bits: 1

# RD03-E radar sensor component
rd03e_radar:
  id: radar_sensor
  uart_id: uart_bus
  # Binary sensor for presence detection
  presence:
    name: "Presence Detected"
    device_class: occupancy
    id: presence_detected
  # Binary sensor for movement detection
  movement:
    name: "Movement Detected"
    device_class: motion
    id: movement_detected
  # Sensor for distance measurement
  distance:
    name: "Detection Distance"
    unit_of_measurement: "m"
    accuracy_decimals: 2
    id: detection_distance
    device_class: distance
  # Configuration settings
  detection_distance: 3.0
  sensitivity: 5

# Add template number entities to control the sensor settings
number:
  - platform: template
    name: "Detection Distance Setting"
    id: detection_distance_setting
    min_value: 0.5
    max_value: 6.0
    step: 0.5
    initial_value: 3.0
    optimistic: true
    mode: slider
    on_value:
      then:
        - lambda: |-
            id(radar_sensor).set_detection_distance(x);

  - platform: template
    name: "Sensitivity Setting"
    id: sensitivity_setting
    min_value: 1
    max_value: 10
    step: 1
    initial_value: 5
    optimistic: true
    mode: slider
    on_value:
      then:
        - lambda: |-
            id(radar_sensor).set_sensitivity(x);